from hikari import User as User
from matter.core.classes.data import Data as Data
from matter.core.classes.ticket import Ticket as Ticket

class TicketManager:
    def __init__(self) -> None: ...
    def newTicket(self, author: User, title: str, description: str) -> Ticket: ...
    def getTicket(self, ticketId: str) -> Ticket | None: ...
    def removeTicket(self, ticketId: int) -> None: ...
