from typing import Any

class Config(object):
    def __init__(self) -> None: ...
    def getStr(self, key: str, default: str) -> str: ...
    def getDict(self, key: str, default: dict[str, Any]) -> dict[str, Any]: ...
    def getBool(self, key: str, default: bool) -> bool: ...
    def getInt(self, key: str, default: int) -> int: ...
