from typing import Any

class Data(object):
    def __init__(self, partition: str) -> None: ...
    def get(self, path: str, default: Any | None = None) -> Any | None: ...
    def put(self, path: str, data: dict[str, Any]) -> None: ...
    def remove(self, path: str) -> None: ...
