from typing import Any, TypeVar

T = TypeVar("T", str, dict[str, Any], bool, int)

class Data:
    def __init__(self, partition: str = "", isConfig: bool = False) -> None: ...
    def getStr(self, key: str, default: str) -> str: ...
    def getDict(self, key: str, default: dict[str, Any]) -> dict[str, Any]: ...
    def getBool(self, key: str, default: bool) -> bool: ...
    def getInt(self, key: str, default: int) -> int: ...
    def put(self, path: str, data: dict[str, Any]) -> None: ...
    def remove(self, path: str) -> None: ...
