# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Python application

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python 3.12
      uses: actions/setup-python@v3
      with:
        python-version: "3.12"
    - name: Install build dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flake8 black isort flake8-bugbear pylint

    - name: Install code dependencies
      run: |
        pip install .
    - name: Lint with pylint
      run: |
        pylint .
    - name: Format with flake8
      run: |
        flake8 .
    - name: Format with black
      run: |
        black .
    - name: Format with isort
      run: |
        isort .
